---
- name: install apache
  apt:
    default_release: stable
    name: apache2
    state: latest

# - name: copy unbound config
#   copy:
#     src: 'files/{{ item }}'
#     dest: '{{ item }}'
#   with_items:
#     - /etc/unbound/unbound.conf.d/caching-recursive.conf
#   notify:
#     - restart unbound
